name: Deploy to S3 and CloudFront
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Build and Deploy
        run: |
          npm install && npm run build

          # Sync specific files and folders to S3 bucket
          aws s3 sync . s3://vvsphani.com \
            --exclude "*" \
            --include "assets/**" \
            --include "css/**" \
            --include "index.html" \
            --include "index.js" \
            --include "license"

          # Get the CloudFront distribution ID from the secret
          CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID

          # Invalidate CloudFront cache
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
